[package]
name = "bins"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "version"

[[bin]]
name = "simple_dual"

[dependencies]
pololu-motoron = { version = "0.1.0", path = ".." }
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }

